language: c

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install gnupg reprepro

before_script:
  - echo -n $priv_gpg_{00..30} >> ~/priv_gpg_base64
  - base64 --decode --ignore-garbage ~/priv_gpg_base64 > ~/priv_gpg
  - gpg --allow-secret-key-import --import ~/priv_gpg
  - echo -n $id_dsa_{00..30} >> ~/.ssh/id_dsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_dsa_base64 > ~/.ssh/id_dsa
  - chmod 600 ~/.ssh/id_dsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"

script:
  - files=(debian/incoming/*.changes debian/incoming/*.deb) ; if [ ${#files[@]} -gt 0 ] ; then reprepro -V -b debian processincoming unstable ; fi

after_success:
  - git add debian/*
  - git commit -m"Incoming packages processed"
  - git branch incoming-processed
  - git checkout master
  - git merge incoming-processed
  - git branch -d incoming-processed
  - git push git@github.com:bguerin/bguerin.github.io.git
